In [ ]:
pip install theano


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 17.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for theano: filename=Theano-1.0.5-py3-none-any.whl size=2668108 sha256=c3fdb85d02d749a33ebdb1876f61723c4714694a7a66f1fe942264753aa08b1f
  Stored in directory: /root/.cache/pip/wheels/d9/e6/7d/2267d21a99e4ab8276f976f293b4ff23f50c9d809f4a216ebb
Successfully built theano


In [ ]:
import torch

In [ ]:
#creating a tensors
t1 = torch.tensor([1,2,3,4])
t2 = torch.tensor([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])

In [ ]:
#printing the tensors
print("Tensor t1:\n",t1)
print("\n Tensor t2:\n",t2)

Tensor t1:
 tensor([1, 2, 3, 4])

 Tensor t2:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [ ]:
#rank of tensors
print("\n Rank of t1:",len(t1.shape))
print("\n Rank of t2",len(t2.shape))



 Rank of t1: 1

 Rank of t2 2


In [ ]:
#shape of tensors
print("\n Rank of t1:",t1.shape)
print("\n Rank of t2",t2.shape)


 Rank of t1: torch.Size([4])

 Rank of t2 torch.Size([3, 4])


In [ ]:
#importing a torch module
import torch
import numpy as np

In [ ]:
#list of values to be stored as tensor
data1 = [1,2,3,4,5,6]
data2 = np.array([1.5,3.4,6.8,9.3,7.0,2.8])

In [ ]:
#creating tesnors and printing
t1 = torch.tensor(data1)
t2 = torch.tensor(data1)
t3 = torch.as_tensor(data2)
t4 = torch.from_numpy(data2)

print("tensor: ",t1,"data type:",t1.dtype,"\n")
print("tensor: ",t2,"data type:",t2.dtype,"\n")
print("tensor: ",t3,"data type:",t3.dtype,"\n")
print("tensor: ",t4,"data type:",t4.dtype,"\n")

tensor:  tensor([1, 2, 3, 4, 5, 6]) data type: torch.int64 

tensor:  tensor([1, 2, 3, 4, 5, 6]) data type: torch.int64 

tensor:  tensor([1.5000, 3.4000, 6.8000, 9.3000, 7.0000, 2.8000], dtype=torch.float64) data type: torch.float64 

tensor:  tensor([1.5000, 3.4000, 6.8000, 9.3000, 7.0000, 2.8000], dtype=torch.float64) data type: torch.float64 



In [ ]:
import torch

In [ ]:
#defining tensor
t = torch.tensor([[1,2,3,4],[5,6,7,8],
                  [9,10,11,12]])

In [ ]:
#reshaping the tensor
print("Reshaping")
print(t.reshape(6,2))

Reshaping
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])


In [ ]:
#resizing the tensor
print("\n resizing")
print(t.resize(2,6))


 resizing
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])


/usr/local/lib/python3.10/dist-packages/torch/_tensor.py:775: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


In [ ]:
#transposing the tensor
print("\n Transposing")
print(t.transpose(1,0))


 Transposing
tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])


In [ ]:
import torch

In [ ]:
#defining two tensors
t1 = torch.tensor([1,2,3,4])
t2 = torch.tensor([5,6,7,8])


In [ ]:
#adding two tensors
print("tensor2 + tesnor1")
print(torch.add(t2,t1))

tensor2 + tesnor1
tensor([ 6,  8, 10, 12])


In [ ]:
#substracting two tensors
print("\n tensor2 - tensor1")
print(torch.sub(t2,t1))


 tensor2 - tensor1
tensor([4, 4, 4, 4])


In [ ]:
#multiplying two tensors
print("\n tensor2 * tensor1")
print(torch.mul(t1,t2))


 tensor2 * tensor1
tensor([ 5, 12, 21, 32])


In [ ]:
#dividing two tensors
print("\n tensor2 / tensor1")
print(torch.div(t2,t1))


 tensor2 / tensor1
tensor([5.0000, 3.0000, 2.3333, 2.0000])
